name: "START_DLT_PIPELINE"

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Select environment to start'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - main

jobs:
  run_pipeline:
    name: "Trigger Remote Start"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Start Pipeline
        working-directory: ./maven_market 
        run: |
          # This command starts the DLT pipeline remotely
          databricks bundle run maven_market_main --refresh-all -t ${{ github.event.inputs.target }}
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_BUNDLE_ENGINE: direct